# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Bathroom', 'Bathroom'), ('Walk', 'Walk'), ('Medicine', 'Medicine'), ('Feeding', 'Feeding')], max_length=1),
        ),
    ]
