# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='feeding_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
