# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 06:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedings', '0002_auto_20170116_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='feeding_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='feeding',
            old_name='feeding_time',
            new_name='time',
        ),
    ]
