# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-13 21:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('animal', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=3)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('microchip_number', models.CharField(blank=True, max_length=30)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
