# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 03:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.CharField(choices=[('D', 'Dog'), ('C', 'Cat')], max_length=3),
        ),
        migrations.AlterField(
            model_name='pet',
            name='microchip_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_id',
            field=models.PositiveIntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
