# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 04:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0002_auto_20170105_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.CharField(choices=[('C', 'Cat'), ('D', 'Dog')], max_length=3),
        ),
    ]
