# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-06 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20170105_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.CharField(choices=[('D', 'Dog'), ('C', 'Cat')], max_length=3),
        ),
    ]
