# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20170116_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.CharField(choices=[('Cat', 'Cat'), ('Dog', 'Dog')], max_length=3),
        ),
    ]
