# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 05:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='walk_time',
            field=models.TimeField(default=datetime.datetime(2017, 1, 16, 5, 6, 11, 607574, tzinfo=utc)),
        ),
    ]
