# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('walks', '0003_auto_20170115_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='walk_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
