# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feedings.Event')),
                ('bathroom_type', models.CharField(choices=[('Pee', 'Pee'), ('Poop', 'Poop')], max_length=4)),
            ],
            bases=('feedings.event',),
        ),
    ]
