# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bathroom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bathroom',
            name='bathroom_type',
            field=models.CharField(choices=[('Pee', 'Pee'), ('Poop', 'Poop')], max_length=4),
        ),
    ]
