# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 07:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0003_auto_20170116_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_type', models.CharField(choices=[('Flea/Tick', 'Poop'), ('Pain Reliever', 'Pain Reliever'), ('Steroids', 'Steroids'), ('Behavior-Modifying', 'Behavior-Modifying'), ('Anti-Inflammatory', 'Anti-Inflammatory'), ('Antibiotic', 'Antibiotic'), ('Chemotherapeutics', 'Chemotherapeutics'), ('Hormones', 'Hormones'), ('Heartworm', 'Pee')], max_length=4)),
                ('medication_time', models.TimeField(default=django.utils.timezone.now)),
                ('medication_date', models.DateField(default=datetime.date.today)),
                ('comments', models.TextField(blank=True)),
                ('pet', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pets.Pet')),
            ],
        ),
    ]
