# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='feedings.Event')),
                ('medication_type', models.CharField(choices=[('Antibiotic', 'Antibiotic'), ('Hormones', 'Hormones'), ('Steroids', 'Steroids'), ('Anti-Inflammatory', 'Anti-Inflammatory'), ('Chemotherapeutics', 'Chemotherapeutics'), ('Behavior-Modifying', 'Behavior-Modifying'), ('Flea/Tick', 'Flea/Tick'), ('Heartworm', 'Heartworm'), ('Pain Reliever', 'Pain Reliever')], max_length=100)),
            ],
            bases=('feedings.event',),
        ),
    ]
