# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medication_type',
            field=models.CharField(choices=[('Heartworm', 'Heartworm'), ('Chemotherapeutics', 'Chemotherapeutics'), ('Flea/Tick', 'Flea/Tick'), ('Anti-Inflammatory', 'Anti-Inflammatory'), ('Behavior-Modifying', 'Behavior-Modifying'), ('Steroids', 'Steroids'), ('Pain Reliever', 'Pain Reliever'), ('Hormones', 'Hormones'), ('Antibiotic', 'Antibiotic')], max_length=4),
        ),
    ]
