# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medication_type',
            field=models.CharField(choices=[('Hormones', 'Hormones'), ('Chemotherapeutics', 'Chemotherapeutics'), ('Antibiotic', 'Antibiotic'), ('Anti-Inflammatory', 'Anti-Inflammatory'), ('Steroids', 'Steroids'), ('Behavior-Modifying', 'Behavior-Modifying'), ('Flea/Tick', 'Flea/Tick'), ('Pain Reliever', 'Pain Reliever'), ('Heartworm', 'Heartworm')], max_length=100),
        ),
    ]
