# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_auto_20170116_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='medication_type',
            field=models.CharField(choices=[('Pain Reliever', 'Pain Reliever'), ('Flea/Tick', 'Flea/Tick'), ('Hormones', 'Hormones'), ('Steroids', 'Steroids'), ('Heartworm', 'Heartworm'), ('Chemotherapeutics', 'Chemotherapeutics'), ('Antibiotic', 'Antibiotic'), ('Behavior-Modifying', 'Behavior-Modifying'), ('Anti-Inflammatory', 'Anti-Inflammatory')], max_length=100),
        ),
    ]
