# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_auto_20170116_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='medication_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='medication_time',
            new_name='time',
        ),
        migrations.AlterField(
            model_name='medication',
            name='medication_type',
            field=models.CharField(choices=[('Chemotherapeutics', 'Chemotherapeutics'), ('Flea/Tick', 'Flea/Tick'), ('Pain Reliever', 'Pain Reliever'), ('Hormones', 'Hormones'), ('Antibiotic', 'Antibiotic'), ('Steroids', 'Steroids'), ('Heartworm', 'Heartworm'), ('Anti-Inflammatory', 'Anti-Inflammatory'), ('Behavior-Modifying', 'Behavior-Modifying')], max_length=100),
        ),
    ]
